from datetime import datetime, date
from sqlalchemy import (
    Column, String, Integer, BigInteger, Numeric, Text, TIMESTAMP, Date, Boolean,
    ForeignKey, UniqueConstraint, Index, JSON
)
from sqlalchemy.dialects.postgresql import JSONB
from .engine import Base


class Universe(Base):
    __tablename__ = "universe"
    symbol = Column(String(10), primary_key=True)
    name = Column(String(100))
    sector = Column(String(50))
    market_type = Column(String(20), default="US_STOCK")
    total_shares = Column(BigInteger)
    float_shares = Column(BigInteger)
    added_at = Column(TIMESTAMP, default=datetime.utcnow)


class DailyKline(Base):
    __tablename__ = "daily_klines"
    symbol = Column(String(10), primary_key=True)
    trade_date = Column(Date, primary_key=True)
    open = Column(Numeric(12, 4))
    high = Column(Numeric(12, 4))
    low = Column(Numeric(12, 4))
    close = Column(Numeric(12, 4))
    adj_close = Column(Numeric(12, 4))
    volume = Column(BigInteger)
    amount = Column(Numeric(18, 2))
    pct_chg = Column(Numeric(8, 4))
    turnover_rate = Column(Numeric(8, 4))
    source = Column(String(50), default="eastmoney_cdp_image")
    fetched_at = Column(TIMESTAMP, default=datetime.utcnow)


class RealtimeQuote(Base):
    __tablename__ = "realtime_quotes"
    symbol = Column(String(10), primary_key=True)
    snap_time = Column(TIMESTAMP, primary_key=True)
    latest_price = Column(Numeric(12, 4))
    prev_close = Column(Numeric(12, 4))
    open = Column(Numeric(12, 4))
    high = Column(Numeric(12, 4))
    low = Column(Numeric(12, 4))
    volume = Column(BigInteger)
    amount = Column(Numeric(18, 2))
    pct_chg = Column(Numeric(8, 4))
    pe_ttm = Column(Numeric(10, 4))
    roe = Column(Numeric(10, 4))
    dividend_yield = Column(Numeric(10, 4))
    week52_high = Column(Numeric(12, 4))
    week52_low = Column(Numeric(12, 4))


class FundFlow(Base):
    __tablename__ = "fund_flow"
    symbol = Column(String(10), primary_key=True)
    trade_date = Column(Date, primary_key=True)
    main_net_inflow = Column(Numeric(18, 2))
    main_net_ratio = Column(Numeric(8, 4))
    net_inflow_5d = Column(Numeric(18, 2))
    score = Column(Numeric(6, 4))


class Ticket(Base):
    __tablename__ = "tickets"
    id = Column(Integer, primary_key=True, autoincrement=True)
    output_date = Column(Date, nullable=False)
    symbol = Column(String(10), nullable=False)
    as_of_date = Column(Date, nullable=False)
    ticket_rank = Column(Integer)
    market_score = Column(Numeric(8, 6))
    catalyst_score = Column(Numeric(8, 6))
    ticket_score = Column(Numeric(8, 6))
    classification = Column(String(50))
    evidence_gate_status = Column(String(50))
    risk_verdict = Column(String(20))
    quality_verdict = Column(String(20))
    lifecycle_stage = Column(String(30))
    run_name = Column(String(100))
    research_run_id = Column(Integer, ForeignKey("research_runs.run_id"))
    # 出票理由字段
    narrative_title = Column(Text)
    business_title = Column(Text)
    risk_summary = Column(Text)
    quality_summary = Column(Text)
    panel_verdict = Column(String(50))
    market_regime = Column(String(20))
    entry_reason = Column(Text)
    # 评分细分字段（用于回测分析）
    institutional_flow_score = Column(Numeric(8, 6))
    social_sentiment_score = Column(Numeric(8, 6))
    raw_market_score = Column(Numeric(8, 6))
    blended_score = Column(Numeric(8, 6))
    breakout_score = Column(Numeric(8, 6))
    risk_penalty = Column(Numeric(8, 6))
    confirmation_score = Column(Numeric(8, 6))
    capital_score = Column(Numeric(8, 6))
    capital_strength = Column(Numeric(8, 6))
    capital_quality = Column(Numeric(8, 6))
    quality_label = Column(String(40))
    capital_state = Column(String(40))
    capital_state_confidence = Column(Numeric(8, 6))
    capital_intent = Column(String(40))
    capital_intent_confidence = Column(Numeric(8, 6))
    accumulation_score = Column(Numeric(8, 6))
    absorption_score = Column(Numeric(8, 6))
    supply_exhaustion_score = Column(Numeric(8, 6))
    demand_persistence_score = Column(Numeric(8, 6))
    markup_score = Column(Numeric(8, 6))
    distribution_score = Column(Numeric(8, 6))
    price_control_score = Column(Numeric(8, 6))
    crowding_score = Column(Numeric(8, 6))
    trap_score = Column(Numeric(8, 6))
    absorption_efficiency = Column(Numeric(8, 6))
    absorption_persistence = Column(Numeric(8, 6))
    upside_control_efficiency = Column(Numeric(8, 6))
    downside_control_efficiency = Column(Numeric(8, 6))
    control_asymmetry = Column(Numeric(8, 6))
    distribution_probability = Column(Numeric(8, 6))
    distribution_stage = Column(String(32))
    distribution_acceleration = Column(Numeric(8, 6))
    distribution_transition_risk = Column(Numeric(8, 6))
    trap_probability = Column(Numeric(8, 6))
    transition_score = Column(Numeric(8, 6))
    late_state_risk = Column(Numeric(8, 6))
    state_age_score = Column(Numeric(8, 6))
    intent_probability = Column(Numeric(8, 6))
    intent_probabilities = Column(JSONB)
    transition_probabilities = Column(JSONB)
    path_distribution = Column(JSONB)
    expected_direction = Column(String(16))
    path_type = Column(String(40))
    t1_probability = Column(Numeric(8, 6))
    t3_probability = Column(Numeric(8, 6))
    t5_probability = Column(Numeric(8, 6))
    capital_thesis = Column(Text)
    invalidation_condition = Column(Text)
    created_at = Column(TIMESTAMP, default=datetime.utcnow)


class ForwardTracking(Base):
    __tablename__ = "forward_tracking"
    id = Column(Integer, primary_key=True, autoincrement=True)
    output_date = Column(Date, nullable=False)
    symbol = Column(String(10), nullable=False)
    as_of_date = Column(Date, nullable=False)
    horizon_days = Column(Integer, nullable=False)
    due_date = Column(Date, nullable=False)
    as_of_close = Column(Numeric(12, 4))
    check_status = Column(String(20), default="pending")
    due_close = Column(Numeric(12, 4))
    forward_return = Column(Numeric(10, 6))
    completed_at = Column(TIMESTAMP)
    track_key = Column(String(100), unique=True)
    ticket_id = Column(Integer, ForeignKey("tickets.id"))
    # 亏损/收益分析
    loss_reason = Column(Text)
    outcome_classification = Column(String(20))
    outcome_reason = Column(Text)
    capital_model_version = Column(String(64))
    capital_validation_status = Column(String(64))
    capital_state_at_entry = Column(String(40))
    capital_intent_at_entry = Column(String(40))
    capital_strength_at_entry = Column(Numeric(8, 6))
    capital_quality_at_entry = Column(Numeric(8, 6))
    capital_score_at_entry = Column(Numeric(8, 6))
    distribution_score_at_entry = Column(Numeric(8, 6))
    trap_score_at_entry = Column(Numeric(8, 6))
    distribution_probability_at_entry = Column(Numeric(8, 6))
    trap_probability_at_entry = Column(Numeric(8, 6))
    quality_label_at_entry = Column(String(40))
    intent_probability_at_entry = Column(Numeric(8, 6))
    path_distribution_at_entry = Column(JSONB)
    predicted_path = Column(String(40))
    state_after_1d = Column(String(40))
    state_after_3d = Column(String(40))
    state_after_5d = Column(String(40))
    state_after_10d = Column(String(40))
    return_1d = Column(Numeric(10, 6))
    return_3d = Column(Numeric(10, 6))
    return_5d = Column(Numeric(10, 6))
    return_10d = Column(Numeric(10, 6))
    path_after_1d = Column(String(40))
    path_after_3d = Column(String(40))
    path_after_5d = Column(String(40))
    path_after_10d = Column(String(40))
    transition_label = Column(String(96))
    label_version = Column(String(64))
    actual_path = Column(String(40))
    actual_intent_proxy = Column(String(40))
    actual_intent_semantic = Column(String(32))
    state_correct = Column(Boolean)
    intent_correct = Column(Boolean)
    path_correct = Column(Boolean)
    created_at = Column(TIMESTAMP, default=datetime.utcnow)


class CapitalDailySnapshot(Base):
    __tablename__ = "capital_daily_snapshot"
    id = Column(BigInteger, primary_key=True)
    symbol = Column(String(10), nullable=False)
    as_of_date = Column(Date, nullable=False)
    research_run_id = Column(Integer, ForeignKey("research_runs.run_id"), nullable=False)
    model_version = Column(String(64), nullable=False)
    data_version = Column(String(64), nullable=False)
    validation_status = Column(String(64), nullable=False)
    statistical_score = Column(Numeric(8, 6))
    capital_score = Column(Numeric(8, 6))
    combined_score = Column(Numeric(8, 6))
    capital_strength = Column(Numeric(8, 6))
    capital_quality = Column(Numeric(8, 6))
    quality_label = Column(String(40))
    dominant_direction = Column(String(16))
    dominant_pressure = Column(Numeric(8, 6))
    distribution_risk = Column(Numeric(8, 6))
    trap_risk = Column(Numeric(8, 6))
    absorption_score = Column(Numeric(8, 6))
    absorption_efficiency = Column(Numeric(8, 6))
    absorption_persistence = Column(Numeric(8, 6))
    upside_control_efficiency = Column(Numeric(8, 6))
    downside_control_efficiency = Column(Numeric(8, 6))
    control_asymmetry = Column(Numeric(8, 6))
    control_regime = Column(String(16))
    control_collapse_score = Column(Numeric(8, 6))
    distribution_probability = Column(Numeric(8, 6))
    distribution_stage = Column(String(32))
    distribution_acceleration = Column(Numeric(8, 6))
    distribution_transition_risk = Column(Numeric(8, 6))
    trap_probability = Column(Numeric(8, 6))
    transition_score = Column(Numeric(8, 6))
    transition_acceleration = Column(Numeric(8, 6))
    state_age_score = Column(Numeric(8, 6))
    late_state_risk = Column(Numeric(8, 6))
    intent_probability = Column(Numeric(8, 6))
    intent_probabilities = Column(JSONB)
    transition_probabilities = Column(JSONB)
    path_distribution = Column(JSONB)
    evidence_json = Column(JSONB)
    created_at = Column(TIMESTAMP, default=datetime.utcnow)


class CapitalEvidence(Base):
    __tablename__ = "capital_evidence"
    id = Column(BigInteger, primary_key=True)
    symbol = Column(String(10), nullable=False)
    as_of_date = Column(Date, nullable=False)
    research_run_id = Column(Integer, ForeignKey("research_runs.run_id"), nullable=False)
    model_version = Column(String(64), nullable=False)
    data_version = Column(String(64), nullable=False)
    evidence_type = Column(String(64), nullable=False)
    value = Column(Numeric(8, 6))
    confidence = Column(Numeric(8, 6))
    availability = Column(String(40), nullable=False)
    source = Column(String(128))
    lookback = Column(String(64))
    semantic = Column(String(16), nullable=False)
    created_at = Column(TIMESTAMP, default=datetime.utcnow)


class CapitalStateHistory(Base):
    __tablename__ = "capital_state_history"
    id = Column(BigInteger, primary_key=True)
    symbol = Column(String(10), nullable=False)
    as_of_date = Column(Date, nullable=False)
    research_run_id = Column(Integer, ForeignKey("research_runs.run_id"), nullable=False)
    model_version = Column(String(64), nullable=False)
    data_version = Column(String(64), nullable=False)
    capital_state = Column(String(40), nullable=False)
    previous_capital_state = Column(String(40))
    state_transition = Column(String(96))
    state_duration = Column(Integer, nullable=False)
    state_confidence = Column(Numeric(8, 6))
    state_reason = Column(Text)
    state_momentum = Column(Numeric(8, 6))
    transition_score = Column(Numeric(8, 6))
    transition_acceleration = Column(Numeric(8, 6))
    evidence_persistence = Column(Numeric(8, 6))
    expected_duration = Column(Integer)
    duration_percentile = Column(Numeric(8, 6))
    late_state_risk = Column(Numeric(8, 6))
    state_age_score = Column(Numeric(8, 6))
    transition_probabilities = Column(JSONB)
    transition_matrix = Column(JSONB)
    semantic = Column(String(16), nullable=False)
    created_at = Column(TIMESTAMP, default=datetime.utcnow)


class CapitalIntent(Base):
    __tablename__ = "capital_intent"
    id = Column(BigInteger, primary_key=True)
    symbol = Column(String(10), nullable=False)
    as_of_date = Column(Date, nullable=False)
    research_run_id = Column(Integer, ForeignKey("research_runs.run_id"), nullable=False)
    model_version = Column(String(64), nullable=False)
    data_version = Column(String(64), nullable=False)
    capital_intent = Column(String(40), nullable=False)
    intent_confidence = Column(Numeric(8, 6))
    intent_probability = Column(Numeric(8, 6))
    intent_probabilities = Column(JSONB)
    intent_alternatives = Column(JSONB)
    expected_direction = Column(String(16))
    continuation_condition = Column(Text)
    invalidation_condition = Column(Text)
    semantic = Column(String(16), nullable=False)
    previous_intent = Column(String(40))
    current_intent = Column(String(40))
    intent_transition = Column(String(96))
    created_at = Column(TIMESTAMP, default=datetime.utcnow)


class CapitalPathPrediction(Base):
    __tablename__ = "capital_path_prediction"
    id = Column(BigInteger, primary_key=True)
    symbol = Column(String(10), nullable=False)
    as_of_date = Column(Date, nullable=False)
    research_run_id = Column(Integer, ForeignKey("research_runs.run_id"), nullable=False)
    model_version = Column(String(64), nullable=False)
    data_version = Column(String(64), nullable=False)
    path_type = Column(String(40), nullable=False)
    t1_probability = Column(Numeric(8, 6))
    t3_probability = Column(Numeric(8, 6))
    t5_probability = Column(Numeric(8, 6))
    path_confidence = Column(Numeric(8, 6))
    path_distribution = Column(JSONB)
    path_sequence = Column(JSONB)
    path_invalidation = Column(JSONB)
    semantic = Column(String(16), nullable=False)
    created_at = Column(TIMESTAMP, default=datetime.utcnow)


class CapitalPredictionOutcome(Base):
    __tablename__ = "capital_prediction_outcome"
    id = Column(BigInteger, primary_key=True)
    forward_tracking_id = Column(Integer, ForeignKey("forward_tracking.id"), nullable=False)
    symbol = Column(String(10), nullable=False)
    as_of_date = Column(Date, nullable=False)
    research_run_id = Column(Integer, ForeignKey("research_runs.run_id"))
    model_version = Column(String(64))
    data_version = Column(String(64))
    state_after_1d = Column(String(40))
    state_after_3d = Column(String(40))
    state_after_5d = Column(String(40))
    state_after_10d = Column(String(40))
    return_1d = Column(Numeric(10, 6))
    return_3d = Column(Numeric(10, 6))
    return_5d = Column(Numeric(10, 6))
    return_10d = Column(Numeric(10, 6))
    path_after_1d = Column(String(40))
    path_after_3d = Column(String(40))
    path_after_5d = Column(String(40))
    path_after_10d = Column(String(40))
    transition_label = Column(String(96))
    label_version = Column(String(64))
    actual_path = Column(String(40))
    actual_intent_proxy = Column(String(40))
    actual_intent_semantic = Column(String(32))
    state_correct = Column(Boolean)
    intent_correct = Column(Boolean)
    path_correct = Column(Boolean)
    semantic = Column(String(16), nullable=False)
    created_at = Column(TIMESTAMP, default=datetime.utcnow)
    updated_at = Column(TIMESTAMP, default=datetime.utcnow)


class CapitalHistoricalLineage(Base):
    __tablename__ = "capital_historical_lineage"
    ticket_id = Column(Integer, ForeignKey("tickets.id"), primary_key=True)
    research_run_id = Column(Integer, ForeignKey("research_runs.run_id"))
    lineage_status = Column(String(32), nullable=False)
    lineage_method = Column(String(64))
    lineage_source = Column(String(64), nullable=False)
    confidence = Column(Numeric(6, 4), nullable=False, default=0)
    evidence = Column(JSONB, nullable=False, default=dict)
    created_at = Column(TIMESTAMP, default=datetime.utcnow)
    updated_at = Column(TIMESTAMP, default=datetime.utcnow)


class CapitalHistoricalOhlcv(Base):
    __tablename__ = "capital_historical_ohlcv"
    id = Column(BigInteger, primary_key=True)
    symbol = Column(String(10), nullable=False)
    trade_date = Column(Date, nullable=False)
    open = Column(Numeric(12, 4))
    high = Column(Numeric(12, 4))
    low = Column(Numeric(12, 4))
    close = Column(Numeric(12, 4))
    volume = Column(BigInteger)
    source_provider = Column(String(64), nullable=False)
    price_semantics = Column(String(64), nullable=False)
    adjustment_mode = Column(String(32), nullable=False)
    timezone = Column(String(64), nullable=False, default="America/New_York")
    frequency = Column(String(16), nullable=False, default="1D")
    created_at = Column(TIMESTAMP, default=datetime.utcnow)
    __table_args__ = (
        UniqueConstraint("symbol", "trade_date", "source_provider", name="uq_capital_historical_ohlcv_symbol_date_provider"),
    )


class CapitalBehaviorDataset(Base):
    __tablename__ = "capital_behavior_dataset"
    id = Column(BigInteger, primary_key=True)
    symbol = Column(String(10), nullable=False)
    as_of_date = Column(Date, nullable=False)
    research_run_id = Column(Integer, ForeignKey("research_runs.run_id"), nullable=False)
    data_version = Column(String(64), nullable=False)
    model_version = Column(String(64), nullable=False)
    feature_version = Column(String(64), nullable=False)
    label_version = Column(String(64))
    capital_model_version = Column(String(64))
    state_model_version = Column(String(64))
    intent_model_version = Column(String(64))
    path_model_version = Column(String(64))
    calibration_version = Column(String(64))
    price = Column(Numeric(12, 4))
    volume = Column(BigInteger)
    liquidity = Column(Numeric(12, 6))
    upward_pressure = Column(Numeric(8, 6))
    downward_pressure = Column(Numeric(8, 6))
    selling_activity = Column(Numeric(8, 6))
    price_damage = Column(Numeric(8, 6))
    expected_price_damage = Column(Numeric(8, 6))
    damage_efficiency = Column(Numeric(8, 6))
    absorption = Column(Numeric(8, 6))
    absorption_efficiency = Column(Numeric(8, 6))
    absorption_persistence = Column(Numeric(8, 6))
    absorption_failure = Column(Numeric(8, 6))
    demand_persistence = Column(Numeric(8, 6))
    supply_exhaustion = Column(Numeric(8, 6))
    markup = Column(Numeric(8, 6))
    distribution = Column(Numeric(8, 6))
    crowding = Column(Numeric(8, 6))
    trap = Column(Numeric(8, 6))
    price_response_efficiency = Column(Numeric(8, 6))
    upside_control_efficiency = Column(Numeric(8, 6))
    downside_control_efficiency = Column(Numeric(8, 6))
    control_asymmetry = Column(Numeric(8, 6))
    control_collapse = Column(Numeric(8, 6))
    capital_state = Column(String(40))
    capital_state_confidence = Column(Numeric(8, 6))
    capital_intent = Column(String(40))
    intent_probability = Column(Numeric(8, 6))
    capital_strength = Column(Numeric(8, 6))
    capital_quality = Column(Numeric(8, 6))
    path_distribution_t1 = Column(JSONB, nullable=False, default=dict)
    path_distribution_t3 = Column(JSONB, nullable=False, default=dict)
    path_distribution_t5 = Column(JSONB, nullable=False, default=dict)
    observed_inputs = Column(JSONB, nullable=False, default=dict)
    derived_features = Column(JSONB, nullable=False, default=dict)
    inferred_state = Column(JSONB, nullable=False, default=dict)
    inferred_intent = Column(JSONB, nullable=False, default=dict)
    predicted_path = Column(JSONB, nullable=False, default=dict)
    future_outcome = Column(JSONB, nullable=False, default=dict)
    source_lineage = Column(JSONB, nullable=False, default=dict)
    eligible_for_training = Column(Boolean, nullable=False, default=False)
    eligible_for_validation = Column(Boolean, nullable=False, default=False)
    eligible_for_test = Column(Boolean, nullable=False, default=False)
    eligibility_reason = Column(String(64), nullable=False)
    dataset_split = Column(String(16))
    created_at = Column(TIMESTAMP, default=datetime.utcnow)
    updated_at = Column(TIMESTAMP, default=datetime.utcnow)


class CapitalPredictionError(Base):
    __tablename__ = "capital_prediction_error"
    id = Column(BigInteger, primary_key=True)
    dataset_sample_id = Column(BigInteger, ForeignKey("capital_behavior_dataset.id"))
    model_version = Column(String(64), nullable=False)
    prediction_date = Column(Date, nullable=False)
    symbol = Column(String(10), nullable=False)
    predicted_state = Column(String(40))
    actual_state = Column(String(40))
    predicted_intent = Column(String(40))
    actual_intent_proxy = Column(String(40))
    predicted_path = Column(String(40))
    actual_path = Column(String(40))
    error_type = Column(String(64), nullable=False)
    error_magnitude = Column(Numeric(12, 6))
    confidence = Column(Numeric(8, 6))
    metadata_json = Column("metadata", JSONB, nullable=False, default=dict)
    created_at = Column(TIMESTAMP, default=datetime.utcnow)


class CapitalModelDrift(Base):
    __tablename__ = "capital_model_drift"
    id = Column(BigInteger, primary_key=True)
    model_version = Column(String(64), nullable=False)
    window_start = Column(Date)
    window_end = Column(Date)
    status = Column(String(32), nullable=False)
    state_accuracy = Column(Numeric(8, 6))
    path_accuracy = Column(Numeric(8, 6))
    calibration_error = Column(Numeric(8, 6))
    distribution_warning_precision = Column(Numeric(8, 6))
    metrics = Column(JSONB, nullable=False, default=dict)
    created_at = Column(TIMESTAMP, default=datetime.utcnow)


class RuntimeDecision(Base):
    __tablename__ = "runtime_decisions"
    id = Column(Integer, primary_key=True, autoincrement=True)
    output_date = Column(Date, nullable=False)
    run_name = Column(String(100))
    final_classification = Column(String(50))
    paper_review_count = Column(Integer)
    market_watchlist_count = Column(Integer)
    universe_count = Column(Integer)
    regime = Column(String(20))
    summary = Column(JSONB)
    created_at = Column(TIMESTAMP, default=datetime.utcnow)


class MarketSnapshot(Base):
    __tablename__ = "market_snapshots"
    trade_date = Column(Date, primary_key=True)
    regime = Column(String(20))
    breadth = Column(Numeric(6, 4))
    momentum = Column(Numeric(8, 6))
    volatility = Column(Numeric(8, 6))
    advance_ratio = Column(Numeric(6, 4))
    equal_weight_benchmark = Column(Numeric(8, 6))
    universe_count = Column(Integer)
    created_at = Column(TIMESTAMP, default=datetime.utcnow)


class LifecycleScoreboard(Base):
    __tablename__ = "lifecycle_scoreboard"
    id = Column(Integer, primary_key=True, autoincrement=True)
    generated_at = Column(TIMESTAMP, default=datetime.utcnow)
    overall = Column(JSONB)
    by_horizon = Column(JSONB)
    by_stage = Column(JSONB)
    by_symbol = Column(JSONB)
    by_regime = Column(JSONB)


class ResearchRun(Base):
    __tablename__ = "research_runs"
    run_id = Column(Integer, primary_key=True, autoincrement=True)
    run_name = Column(String(100), nullable=False)
    output_date = Column(Date, nullable=False)
    started_at = Column(TIMESTAMP, default=datetime.utcnow)
    finished_at = Column(TIMESTAMP)
    candidate_count = Column(Integer)
    pass_count = Column(Integer)
    status = Column(String(20), default="running")
    git_commit = Column(String(40))
    config = Column(JSONB)
    error_message = Column(Text)


class FactorSnapshot(Base):
    __tablename__ = "factor_snapshots"
    id = Column(Integer, primary_key=True, autoincrement=True)
    trade_date = Column(Date, nullable=False)
    symbol = Column(String(10), nullable=False)
    prior_5d_momentum = Column(Numeric(8, 6))
    prior_20d_momentum = Column(Numeric(8, 6))
    five_day_acceleration = Column(Numeric(8, 6))
    relative_strength = Column(Numeric(8, 6))
    volume_weighted_momentum = Column(Numeric(8, 6))
    rsi_14 = Column(Numeric(6, 2))
    momentum_quality = Column(Numeric(6, 4))
    breakout_score = Column(Numeric(6, 4))
    reversal_quality = Column(Numeric(6, 4))
    volume_confirmation = Column(Numeric(8, 6))
    closing_strength_5d = Column(Numeric(6, 4))
    dollar_volume_20d = Column(Numeric(18, 2))
    market_score = Column(Numeric(8, 6))
    structured_score = Column(Numeric(8, 6))
    blended_score = Column(Numeric(8, 6))
    theme_strength = Column(Numeric(8, 6))
    announcement_catalyst = Column(Numeric(8, 6))
    regime = Column(String(20))
    created_at = Column(TIMESTAMP, default=datetime.utcnow)
    __table_args__ = (
        UniqueConstraint("trade_date", "symbol", name="uq_factor_snapshots_date_symbol"),
    )


class CeleryTask(Base):
    __tablename__ = "celery_tasks"
    task_id = Column(String(55), primary_key=True)
    task_name = Column(String(100))
    status = Column(String(20), default="pending")
    started_at = Column(TIMESTAMP)
    finished_at = Column(TIMESTAMP)
    result = Column(JSONB)
    error_message = Column(Text)
    retry_count = Column(Integer, default=0)
    created_at = Column(TIMESTAMP, default=datetime.utcnow)
